### PR TITLE
g-suite require full name

### PR DESCRIPTION
**Pull request by vikasrnv**
#544 

- g-suite onboard problem solved
- now every applicant needs to fill `last_name` also .
 
- Client applications are requested to update these two field in employee_application form.     
     - remove
         -   `name`    
    - add 
        -  `first_name` 
        -  `last_name`

### CODE REVIEW

**Comment by vikasrnv** [comment]
my test `Travis CI` failed as the test case are written in `employee-portal/tests/Feature/HR/ApplicationTest.php` based on previous application form data. so they are conflicting with the changes which I have made on `employee-portal/app/Models/HR/Applicant` file. 

I think there is a need for updating the test cases.
so what should be the ideal changes that I need to make?
@bohraji @rathorevaibhav

**Comment by vikasrnv** [comment]
now I have put the code in `app/Http/Controllers/HR/ApplicantController.php` insteat of  `employee-portal/app/Models/HR/Applicant` due to which test is pass.

**Comment by vikasrnv** [comment]
@bohraji 
So we have also considered this two problem before starting the issue.
 - @rathorevaibhav is already aware of the effect of this in other website and I also mention in it in `pr 
   description`.
- We already having functionality `split_name` which split the name into `first_name` and `last_name` so
  there will be no error because of this when we onbord user.
- The problem was when an applicant submits their application by entering only `fisrt_name` then 
  `split_name` send last_name as `null` due to which required field last_name of `G-suite` give the error.
  so as a solution we make application field also required.

**Comment by rathorevaibhav** [comment]
We need to fix the forms in our WP site to accommodate these changes. Putting this on hold until that is fixed.

Will update once WP changes are done.

**Pull request merged**
