### PR TITLE
463 status modal doesn't disappear on clicking x button

### PR DESCRIPTION
**Pull request by abhishek-pokhriyal**
#463 

Reason for  problem: 
@rathorevaibhav pointed out that jQuery code for closing the modal was defined before (above) the VueJs code that prepares the book `index.blade.php` page. So jQuery code for closing the modal was being executed before the modal was even rendered.

Our solution:
jQuery for closing the modal is executed when the document is ready that is the jQuery code is now put inside `$document.ready()`

### CODE REVIEW

**Comment by abhishek-pokhriyal** [comment]
@wevekamola and @bohraji please review.

**Comment by abhishek-pokhriyal** [comment]
@wevekamola and @bohraji please review.

**Comment by abhishek-pokhriyal** [comment]
@wevekamola and @bohraji please review.

**Comment by wevekamola** [comment]
@abhishek-pokhriyal The current implementation looks like a temporary fix as the same functnality is working on the home page. I think the issue needs a bit more debugging.

**Comment by rathorevaibhav** [comment]
Works as expected. Merging.

**Pull request merged**
