### PR TITLE
#250 update json column to text for support across mysql versions

### PR DESCRIPTION
**Pull request by bohraji**

### CODE REVIEW

**Comment by bohraji** [comment]
@rathorevaibhav Found the bug for failed builds Solution based on [link](https://github.com/spatie/laravel-medialibrary/issues/563)

**Comment by rathorevaibhav** [comment]
Great @bohraji 🙌

**Comment by rathorevaibhav** [comment]
To clarify, we don't have to run the migration on our environments, right? @bohraji

**Comment by bohraji** [comment]
@rathorevaibhav I changed the existing migration and the type of the column. We'll need to perform a rollback and then migrate again. That will bring all the database in a consistent state. If a lot of users have run it, then we can create a new migration.

**Comment by bohraji** [comment]
@rathorevaibhav Added new migration and update existing one. This was done as the Travis check was breaking in creating the original JSON type column. Also, new migration added so that systems that have data in the system can also update their column and keep the project consistent.

**Comment by rathorevaibhav** [comment]
Checked this PR :

- [ ] For duplication.
- [ ] For performance. 
- [ ] Usage of recursive methods, loops, and algorithms.
- [ ] For readability and understanding. 
- [ ] For functions with multiple responsibilities.
- [ ] For scope of refactoring. 
- [ ] For coupling
- [ ] For alternative approaches to the implementation. 
- [ ] For how the change impacts other parts of the system.
- [ ] For validations. client side and server side validations are present.

For more insights on code reviews checkout our [guidelines](https://docs.google.com/document/d/1Sa-XYJEmGwrOM5gk5zoan_Z6j90ylibmCmt331361nw/edit#).

**Pull request merged**
