### PR TITLE
337 removed reason for eligibility

### PR DESCRIPTION
**Pull request by Satendra-SR**
> **What I have done yet:**
* Created a **new** migration for removing reason_for_eligibility from `hr_application` table.
* Remove the code from `application/edit.blade.php` that was retriving the `reason_for_eligibility` from the database.
* In `ApplicantRequest.php` the data related to `reason_for_eligibility` was coming from **API** request. I have **removed** it as we don't want any special request for reason_for_eligibility. It will come with `form_data` too.
* In `Applicant.php` I **removed** the code that was use to store the `reason_for_eligibility`.

### CODE REVIEW

**Comment by nishanth-kd** [comment]
1. Which issue is this for @Satendra-SR ?
2. Please provide me what you've done corresponding to the requirements. Not description of your code, please checkout @rathorevaibhav's PRs for help in what should go inside the description. 
3. Resolve conflicts and then reassign for review.

**Comment by Satendra-SR** [comment]
Sorry for the inconvenience.
This PR is for #337.
> What I did :
* I have to remove `reason_for_eligibiliy` from the **table** `hr_application`.
* The field `reason_for_eligibility` moved inside the `hr_application_meta` **table** as a `key-value` pair.

So **according to my understanding**, I **don't** have to create a new column inside the `hr_application_meta`. The data related to `reason_for_eligibility` will comes with the `form_data` as a key-value pair in json form and we have to extract reason_for_eligibility from the json data.

**Comment by Satendra-SR** [comment]
#337 
@nishanth-kd 
resolved conflicts.
please review it.

**Comment by rathorevaibhav** [comment]
@nishanth-kd There was some confusion on the requirements during handover. [I've put more details](https://github.com/ColoredCow/employee-portal/issues/337#issuecomment-398669572) on top of Satendra's comment to briefly explain what the requirements are.

**Pull request merged**
